// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Timer struct {
	ID          string    `json:"id"`
	Title       string    `json:"title"`
	TimeElapsed int       `json:"timeElapsed"`
	CreatedAt   time.Time `json:"createdAt"`
}

type UpdatedTimer struct {
	ID          string `json:"id"`
	Title       string `json:"title"`
	TimeElapsed int    `json:"timeElapsed"`
}
